version: "3.9"

services:
  quarto:
    init: true
    environment:
      DISPLAY:
    build: 
      context: .
      dockerfile: Dockerfile
    user: 0:0
    image: anielsen/quarto-16-texlive-python-julia:latest
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
    #env_file:
    #  - quarto-docker.env
    working_dir: /opt/project
